import type { Metadata } from "next";
import "./globals.css";
import ClientAnimations from "./_components/shared/ui/ClientAnimations";
import Navigation from "./_components/shared/layout/Navigation";
import Footer from "./_components/shared/layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Navigation />
        <ClientAnimations />
        {children}
        <Footer />
      </body>
    </html>
  );
}
